[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "icu-sepsis-helpers"
version = "1.0.0"
dependencies = [
  "gymnasium>=0.28.1",
  "gym>=0.21.0",
  "tqdm>=4.65.0",
  "icu-sepsis>=1.0.0"
]
requires-python = ">=3.10"
authors = [
  {name = "Kartik Choudhary"},
  {name = "Dhawal Gupta"},
  {name = "Philip S. Thomas"},
]
maintainers = [
  {name = "Kartik Choudhary", email = "kartikchoudh@cs.umass.edu"},
]
description = "Helper package to build the ICU-Sepsis environment from raw data."
readme = "README.md"
license = {file = "LICENSE.txt"}
keywords = ["sepsis", "icu", "reinforcement-learning"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
