[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "icu-sepsis"
version = "0.1.0"
dependencies = [
  "gymnasium>=0.28.1",
  "gym>=0.21.0",
  "tqdm>=4.65.0",
  "scipy>=1.12.0",
  "matplotlib>=3.8.2",
  "pandas>=2.2.0",
  "pyyaml>=6.0.1",
  "scikit-learn>=1.4.0"
]
requires-python = ">=3.10"
authors = [
  {name = "Anonymized"}
]
maintainers = [
  {name = "Anonymized"},
]
description = "Python implementation of the ICU-Sepsis environment."
readme = "README.rst"
license = {file = "LICENSE.txt"}
keywords = ["sepsis", "icu", "reinforcement-learning"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
